language: python
python:
  - 3.5
  - 3.6
install:
  - pip install pep8
  - pip install codecov
  - pip install coveralls
script:
  - pep8 .
  - coverage run --source=src setup.py test
after_success:
  - coveralls
  - codecov
