language: python
python:
  - 3.5
  - 3.6
install:
  - pip install pycodestyle
  - pip install codecov
  - pip install coveralls
script:
  - pycodestyle .
  - coverage run --source=neko setup.py test
after_success:
  - coveralls
  - codecov
